---

- name: Install common python packages
  apt:
    state: latest
    name:
        - python3-dev
        - python3-pip

- name: Adding Python 3.6 PPA
  apt_repository: repo=ppa:jonathonf/python-3.6 state=present

- name: Install python 3.6
  apt:
    state: present
    name: python3.6
    update_cache: yes

- name: Delete all existing .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  changed_when: false

- name: Delete all __pycache__ folders
  command: find . -type d -name '__pycache__' -exec rm -r {} +
  args:
    chdir: "{{ project_path }}"
  changed_when: false

- name: Deleting all existing .sqlite databases
  command: find . -name '*.sqlite' -delete
  args:
    chdir: "{{ project_path }}"
  changed_when: false

- name: Deleting all existing database migrations
  command: find . -name '*_.py' -delete
  args:
    chdir: "{{ project_path }}/migrations/versions/"
  changed_when: false

- name: Upgrading pip
  command: "{{ pip_path }} install --upgrade pip"
  become: yes

- name: Install 'virtualenv' package
  pip:
    name: virtualenv
    executable: pip3

- name: Create virtualenv
  become: no
  pip:
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: python3.6
    requirements: "{{ requirements_file }}"

- name: Activate virtualenv on login
  lineinfile: dest=~/.bashrc line='. {{ virtualenv_path }}/bin/activate'
  become: no

- name: Adding executable permissions to migrate.py
  file: dest="{{ project_path }}/migrate.py" mode=a+x

- name: Spawning a fresh sqlite database and generating model migrations
  shell: "{{ python_path }} migrate.py db migrate"
  args:
    chdir: "{{ project_path }}"

- name: Applying model migrations
  shell: "{{ python_path }} migrate.py db upgrade"
  args:
    chdir: "{{ project_path }}"
